version: 0.0
os: linux
files:
  - source: /
    destination: /home/todoapp
hooks:
  # BeforeInstall:
  #   - location: scripts/env.sh
  #     runas: root
  #     timeout: 500

  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 3500
