version: 0.0
os: linux
files:
  - source: /
    destination: /home/todoapp
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: root
      timeout: 60000

  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 3500
