version: 0.0
os: linux
files:
  - source: /
    destination: /home/todoapp
hooks:
  # ApplicationStop:
  #   - location: scripts/stop.sh
  #     runas: root
  #     timeout: 600
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 3500
