version: 0.2
environment_variables:
  plaintext:
    jwtPrivateKey:1234
phases:
  install:
    nodejs: 10
    commands:
     - echo "installing nodejs"
     - echo "installing dependencies..."
     - npm install
  pre_build:
    commands:
      - echo "prebuild phase"
  build:
    commands:
      - echo "build phase"
      - echo "running tests..."
      - npm test
  post_build:
    commands:
      - echo "post-build phase"
