version: 0.2

phases:
  install:
    nodejs: 10
    commands:
     - echo "installing nodejs"
  pre_build:
    commands:
      - echo "prebuild phase"
  build:
    commands:
      - echo "build phase"
      - echo "running tests..."
      - export jwtPrivateKey=1234
      - npm test
  post_build:
    commands:
      - echo "post-build phase"
