version: "3"
services:
  mongo:
    image: mongo

    ports:
      - 27017:27018

  todo-app:
    build: ../js-todoapp
    container_name: todo-app
    ports:
      - 5000:5000
    links:
      - mongo
    depends_on:
      - mongo
